### ISSUE TITLE
Drop the 1.9 testing branch

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo-testing#107]
It was raised on apache/accumulo#1312 that the testing repo's 1.9 branch was not in a good state, and it was argued that we shouldn't be updating it, instead keeping the 1.9 testing code with the main 1.9 code base, like it has been.

We could merge the 1.9 branch into the master branch with `-sours` to preserve the 1.9 history before deleting it.

I'll leave this issue open for at least a few days, for comment, before taking any action.

**Comment by milleruntime** [comment]
Dropped

**Comment by ctubbsii** [comment]
Looks like the head of 1.9 (200c7f1726d9e9771114ae8cb006c1297e2e996c) was already merged to master.
