### ISSUE TITLE
Incorrect authorizations selected by continous scanners and walkers 

### ISSUE THREAD

**Issue by mandarinamdar** [apache/accumulo-testing#114]
Authorizations configured for continous scanners and walkers in accumulo-testing.properties in "test.ci.common.auths" incorrectly interpreted as single character each instead of | delimited. Like if  
test.ci.common.auths=SYS,HR,ADM|SYS,ADM is defined. Authorizations chosen are S,Y,S,H,R ... and so on instead of "SYS,HR,ADM" , "SYS,ADM" and so on. 

The issue looks to be in  authValue.split("|") call in ContinuousEnv.java. The code is not considering | as  a metacharacter in regex. It will require escape character to define | in the split function call. something like authValue.split("\\|") to handle the desired functionality correctly.

**Comment by ctubbsii** [comment]
Fixed by #115
