### ISSUE TITLE
Update CI to use Compaction Planner

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo-testing#145]
Continuous Ingest is still using `BasicCompactionStrategy`, which has been deprecated in favor of the new compaction code. This needs to be replaced with a CompactionPlanner, most likely `DefaultCompactionPlanner` will work fine. This may just be a configuration change.

This would be great to do for the 2.1 release testing.

**Comment by milleruntime** [comment]
It may be as simple as changing these properties:
https://github.com/apache/accumulo-testing/blob/main/conf/accumulo-testing.properties#L44-L47

**Comment by DomGarguilo** [comment]
It does seem like the tables default to use `DefaultCompactionPlanner`. Do you think its a good idea to still try and set them explicitly in the props file or just remove the deprecated `BasicCompactionStrategy`? @milleruntime
