### ISSUE TITLE
Replace deprecated properties with their replacements

### ISSUE THREAD

**Issue by Manno15** [apache/accumulo-testing#148]
PR https://github.com/apache/accumulo/pull/2171/ renamed WALOG properties to be WAL instead. There are a few instances inside accumulo-testing that use the deprecated WALOG variant that should be replaced by the WAL counterpart (see #147  as an example of such issue).

**Comment by Manno15** [comment]
There appears to only be one more location for walog and that is in `RollWALPT'. However, I think this issue could be expanded to replace other deprecated properties inside accumulo-testing. Such as `TSERV_SORT_BUFFER_SIZE `inside `Config.java` which should be replaced with `TSERV_WAL_SORT_BUFFER_SIZE`

**Comment by DomGarguilo** [comment]
I think these were taken care of in https://github.com/apache/accumulo-testing/pull/181. I don't see any more use of deprecated properties right now.

Closing as completed by #181.
