### ISSUE TITLE
Clarify how to run individual performance tests

### ISSUE THREAD

**Issue by DomGarguilo** [apache/accumulo-testing#157]
~~While working on #156 I realized it would be helpful to be able to run individual performance tests. As it stands, the only option is to run all the tests in order which takes quite a while. If any of the tests hang or error out, it stops the run of the remaining tests. Would be nice to be able to pass a parameter, the name of an individual test to run, similar to how cinigest works with its multiple components.~~

It doesn't seem there is any place that explains how to run a single Performance test. It would be nice if that was explained somewhere.

**Comment by Manno15** [comment]
I believe you can run individual PTs with something like the following: 
`./bin/performance run results org.apache.accumulo.testing.performance.tests.DurabilityWriteSpeedPT`

**Comment by DomGarguilo** [comment]
> I believe you can run individual PTs with something like the following:
> `./bin/performance run results org.apache.accumulo.testing.performance.tests.DurabilityWriteSpeedPT`

Whoops. Looks like you're right. I assume that is what is meant by `[filter]` in `run <output dir> [filter]` from the usage/help page here:
```
dgarguilo@thor:~/github/accumulo-testing$ ./bin/performance
Unknown command : 

Usage: performance-test <command> (<argument>)

Possible commands:
  run <output dir> [filter]        Runs performance tests.
  compare <result 1> <result 2>    Compares results of two test.
  csv {files}                      Converts results to CSV
  list                             List the performance test
```

Maybe this ticket can be repurposed to serve to make the usage of `[filter]` more clear. Possibly in the [readme](https://github.com/apache/accumulo-testing#performance-test) or in the usage/help page in shell.

**Comment by DomGarguilo** [comment]
> I believe you can run individual PTs with something like the following:
> `./bin/performance run results org.apache.accumulo.testing.performance.tests.DurabilityWriteSpeedPT`

Looks like you can also use just the test name. 
e.g.
`./bin/performance run results DurabilityWriteSpeedPT`

I think I'll just make a PR to add a note to the readme outlining this.
