### ISSUE TITLE
Maven build fails

### ISSUE THREAD

**Issue by Manno15** [apache/accumulo-testing#169]
Build for accumulo-testing is failing with the following errors:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project accumulo-testing: Compilation failure: Compilation failure: 
[ERROR] /home/jeffrey/git/accumulo-testing/src/main/java/org/apache/accumulo/testing/randomwalk/Module.java:[227,89] incompatible types: boolean cannot be converted to java.util.concurrent.BlockingQueue<java.lang.Runnable>
[ERROR] /home/jeffrey/git/accumulo-testing/src/main/java/org/apache/accumulo/testing/randomwalk/bulk/Setup.java:[64,9] incompatible types: boolean cannot be converted to java.util.concurrent.BlockingQueue<java.lang.Runnable>
```
The current commit is 711d28e83a91cbaa0754064a7d72c0f975f7de31 though I have had successful builds on this commit. 
Command ran was maven clean package.

**Comment by DomGarguilo** [comment]
It looks like its using the wrong method call for some reason.
```
Candidates for method call ThreadPools.createFixedThreadPool(1, "RandomWalk Runner", false) are:    
ThreadPoolExecutor createFixedThreadPool(int, String, boolean)  
ThreadPoolExecutor createFixedThreadPool(int, String, BlockingQueue<Runnable>, boolean)   
ThreadPoolExecutor createFixedThreadPool(int, long, TimeUnit, String, boolean)
```
Its trying to use the second one where the first should be used.

**Comment by Manno15** [comment]
This is because `ThreadPoolExecutor createFixedThreadPool(int, String, boolean)` no longer exists inside `ThreadPools.java` in accumulo. It was removed with the OpenTelemetry changes since we don't need to specify `enableTracing`. I will have a PR that changes the two classes in accumulo-testing to just using the (int, String) that replaced it.
