### ISSUE TITLE
Update agitator to read cluster.yml

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo-testing#183]
This ticket is for a solution to have the agitator scripts read the new cluster.yml file. The files referenced in the agitator scripts (master-agitator.pl, tserver-agitator.pl, datanode-agitator.pl) no longer exist since https://github.com/apache/accumulo/pull/2238. Related to #182 

One solution would be to use the perl library "tiny" to real the YAML file but this will require the install of an additional perl package. For example, if the test cluster were running centos it would need to have the package [perl-yaml-tiny](https://centos.pkgs.org/7/centos-x86_64/perl-YAML-Tiny-1.51-6.el7.noarch.rpm.html) installed. I am not sure if this is the best solution.

**Comment by dlmarion** [comment]
Something I just thought of is to do what the [accumulo-cluster](https://github.com/apache/accumulo/blob/main/assemble/bin/accumulo-cluster#L69) script does. It invokes a Java class to parse the yaml file and outputs the information in a key-value format.

I have never really looked at the agitator scripts before, it looks like they just start/stop/restart/kill processes. I think we could make the scripts more modular, reuse some code, and maybe include other types of failure. For example, the old Netflix Chaos Monkey [scripts](https://github.com/Netflix/SimianArmy/tree/master/src/main/resources/scripts) use Linux host commands to introduce various things into the environment - high CPU / IO usage, packet loss, packet latency,  packet corruption, bad routing, etc.

**Comment by milleruntime** [comment]
> Something I just thought of is to do what the [accumulo-cluster](https://github.com/apache/accumulo/blob/main/assemble/bin/accumulo-cluster#L69) script does. It invokes a Java class to parse the yaml file and outputs the information in a key-value format.

I like this idea. There is a bash script calling the perl scripts so we could probably just eliminate the perl scripts.
