### ISSUE TITLE
Make continuous ingest delete data

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo-testing#20]
apache/accumulo#537 was a WAL recovery bug where deleted data could possibly come back.  This flaw was not found through testing.  It would be nice to delete data in the continuous ingest test to cover this case.  This could be done by periodically deleting a previously written set of linked list.  The linked list would need to be deleted in reverse order to avoid false positives in the test. Could do something like the following.

```
while (true) {
   //write 1,000,000 linked list of 25 nodes
   if(random.nextInt(10) == 0) {
       //delete previously written 1,000,000 linked list of 25 nodes in reverse order
   }
```

**Comment by Manno15** [comment]
Additional subtask related to this: https://issues.apache.org/jira/browse/ACCUMULO-2204
