### ISSUE TITLE
Add performance test for group commit

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo-testing#67]
When many clients write data to the same tablet server at around the same time their data should be synced to the write ahead log as a group.  If group commit is not working properly it can cause performance problem for many clients that will not be seen for a single client.  It would be nice to have a performance test that specifically checks for this.

I created a project to do this in the past.  Not sure what state it is in.  

  https://github.com/keith-turner/mutslam

Would be nice to test group commit performance for mutations and conditional mutations.

**Comment by elinaawise** [comment]
I am looking into this.

**Comment by elinaawise** [comment]
@keith-turner I think I misunderstood your intent for issue #30.  Is this ticket (#67) to include mutations and conditional mutations tests for group commits and issue #30 for creating only a conditional mutations PT?
