### ISSUE TITLE
Create script that automates setting up EC2 test cluster

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo-testing#78]
When testing Accumulo I often go through the following task manually.

 * Build snapshot version of Accumulo locally and copy it to Muchos dir
 * Use Muchos to setup a cluster with that snapshot tarball
 * After Muchos sets up the cluster :
    * git clone and  mvn install the same snapshot version of Accumulo
    * git clone accumulo testing repo and build it.

It may be nice to have script that does this.  The argument for the script would be the following :
 * URL for Accumuo git repo and a branch in that repo
 * URL for Accumuo testing repo and a branch in that repo
 * Local dir where muchos is setup.

This script would setup the EC2 cluster with the version of Accumulo from the git repo.  It would also setup accumulo testing on the cluster from the git repo.

**Comment by rcarterjr** [comment]
Working on this now. Since we are assuming that the user already has Accumulo, it may be more useful to have their local path as an argument instead of the URL of the git repo. Is this ok or am I missing something?

**Comment by keith-turner** [comment]
@rcarterjr  I was thinking of a URL because the repo will need to also be cloned and built on the remote cluster

**Comment by keith-turner** [comment]
I started working on the following when I was doing testing for 2.0.0 RC1.  There is not much there.  Just a script I could run on the cluster to setup accumulo and accumulo-testing.

https://github.com/keith-turner/accumulo-testing/tree/automate-everything/cluster-test

**Comment by rcarterjr** [comment]
How should I get the path to the user's local Accumulo directory in your first bullet point? Should I use a global variable or should I prompt the user for their path?

**Comment by keith-turner** [comment]
> How should I get the path to the user's local Accumulo directory in your first bullet point? 

I was thinking that locally Accumulo would be cloned to a tmp directory and built from there.   This would make it much more likely that same version of the code is used everywhere.

**Comment by keith-turner** [comment]
I am setting up a cluster to run some test today.  I took some notes on what did.  I also opened apache/fluo-muchos#260

```bash
# ran the following on my local machine

cd ~/git/accumulo
git checkout 2.0
mvn clean package -DskipTests
cp assemble/target/accumulo-2.0.0-SNAPSHOT-bin.tar.gz ~/git/muchos/conf/upload/
cd ~/git/muchos
sha256sum conf/upload/accumulo-2.0.0-SNAPSHOT-bin.tar.gz

# edit conf/checksums  TODO open issue in muchos
# ensure accumlo version is correct in muchos config


./bin/muchos launch -c bulkCi
./bin/muchos setup -c bulkCi
./bin/muchos ssh -c bulkCi

# following is executing on the cluster.. somehow maybe the following could be munged from the git URL+branch...
wget https://raw.githubusercontent.com/keith-turner/accumulo-testing/automate-everything/cluster-test/setup-software.sh
chmod 755 ./setup-software.sh
./setup-software.sh
```

**Comment by keith-turner** [comment]
One long term goal for this would be to take the following inputs : 

 * Muchos config
 * Accumulo config
 * Accumulo git url+branch
 * Accumulo testing git url+branch
 * Muchos url+branch
 * Test script

And using that instantiate a cluster with that software installed and run the test.    We don't have to start with that, we can move there in small steps.
